config/routes.rb
Rails.application.routes.draw do

  
  resources :bottlecaps
  root "bottlecaps#index"
  get 'noodling' => "bottlecaps#noodling"
  get 'search' => 'bottlecaps#search'
  get "tagged/:tag", to: "bottlecaps#tagged", as: "tag"
  
end

app/models/bottlecap.rb
class Bottlecap < ActiveRecord::Base
  acts_as_taggable
  acts_as_taggable_on :cap_details, :drink_details
  
  before_create do
    self.drink_detail_list.add(self.drink, self.brand, self.parent)
  end
  
  def is_complete?
    [self.brand, self.parent].include?(nil) ? false : true
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bottlecaps_controller.rb
class BottlecapsController < ApplicationController
  def bottlecap_params
    params.require(:bottlecap).permit(:drink, :brand, :parent, :image, :tag_list, :cap_detail_list, :drink_detail_list, :pinned, :favorite)
  end
  
  def index
    @bottlecaps = Bottlecap.all
    render 'bottlecaps'
  end
  
  def new
    @bottlecap = Bottlecap.new
    @brands = Bottlecap.uniq.pluck(:brand).sort
    @parents = Bottlecap.uniq.pluck(:parent).sort
  end
  
  def noodling
    @bottlecaps = Bottlecap.all
    render 'noodling'
  end
  
  def search
    search_term = params[:tag]
    redirect_to "/tagged/#{search_term}"
  end
  
  def tagged
    @bottlecaps = Bottlecap.tagged_with(params[:tag], wild: true, any: true)
    # @bottlecaps += Bottlecap.where("drink ILIKE ? OR brand ILIKE ? OR parent ILIKE ?", "%#{params[:tag]}%", "%#{params[:tag]}%", "%#{params[:tag]}%")
    # @bottlecaps += Bottlecap.where("drink ILIKE ?", params[:tag])
    
    # redirect_to "/tagged/#{params[:tag]}"
    render 'bottlecaps'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bottlecaps_helper.rb
module BottlecapsHelper
end

app/views/bottlecaps/_panel.html.erb
      <div class="thumbnail">
        <div class="caption">
          <p><%= cap.drink %></p>
          <%= image_tag (cap.image || "http://placehold.it/200/200"), class: "icon" %>
          <p><small>from <%= cap.brand %>, by <%= cap.parent %></small></p>
          <i class="fa fa-star" style="color:yellow;"></i>
          <% cap.cap_detail_list.each do |tag| %>
            <a href=<%= tag_path(tag) %> class="btn btn-xs btn-default"><%= tag %></a>
          <% end %>
        </div>
      </div>

app/views/bottlecaps/bottlecaps.html.erb
<!DOCTYPE html>
<html>

<!-- TO DO: Add if-then to determine if the brand part is really needed (ie, if there is no particular brand or if it's the same as the parent --> 
  <body>
    <% @bottlecaps.each do |cap| %>
      <div class="col-sm-2 col-xs-3">
        <div class="thumbnail">
          <div class="caption">
            <p><%= cap.drink %></p>
            <%= image_tag (cap.image || "http://placehold.it/200/200"), class: "icon" %>
            <p><small>from <%= cap.brand %>, by <%= cap.parent %></small></p>
            <% cap.cap_detail_list.each do |tag| %>
              <a href=<%= tag_path(tag) %> class="btn btn-xs btn-default"><%= tag %></a>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/bottlecaps/new.html.haml
.container
  .row
    .col-md-6-offset-3
      .panel.panel-default
        .panel-heading New bottlecap
        .panel-body
          = simple_form_for @bottlecap do |f|
            = f.input :drink
            .row
              .col-md-6.col-sm-6.inputs
                = f.input :brand
                = f.input :parent
              .col-md-6.col-sm-6.selections
                = simple_form_for @bottlecap do |x|
                  = x.input :brand, as: :select, label: "Existing brands", include_blank: :true, collection: @brands
                  = x.input :parent, as: :select, label: "Existing parents", include_blank: :true, collection: @parents
            = f.label :favorite
            = f.check_box :favorite
            = f.label :pinned
            = f.check_box :pinned
            = f.input :cap_detail_list
            = f.input :notes, as: :text
            .divider
            = f.button :submit

app/views/bottlecaps/noodling.html.erb
<!-- TO DO: Add if-then to determine if the brand part is really needed (ie, if there is no particular brand or if it's the same as the parent --> 
<head>
  <%= stylesheet_link_tag "noodling.css" %>

</head>

<div class="container">
  <div class="grid">
  <% @bottlecaps.each do |cap| %>
    <div class="grid-item clearfix">
      <div class="grid-item-content">
        <p class="drink-name"><%= cap.drink %></p>
        <img src="http://placehold.it/100x100/00bfff" class="thumb">
        <div class="details">
          <p class="drink-name-big"><%= cap.drink %></p>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="assets/testing.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <title>Workspace</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <a href=<%= root_path %> class="navbar-brand">Bottlecaps</a>
        <%= form_tag(search_path, :method => "get") do %>
          <%= text_field_tag :tag, nil, placeholder: "Search" %>
        <% end %>
      </div>
    </nav>
  
  <%= yield %>
  
  </body>
</html>